#!/usr/bin/perl
use strict;
use warnings;
use App::Plotr;

App::Plotr->run;

=head1 OVERVIEW

For help with App::Plotr, run "plotr help"

=cut

__END__

# FAKE_RELEASE=1 minil release

perl -I lib/ script/plotr help

# venn
perl -I lib/ script/plotr venn t/rocauc.result.tsv t/mcox.05.result.tsv t/mcox.result.tsv
perl -I lib/ script/plotr venn t/rocauc.result.tsv t/mcox.05.result.tsv --device png --percent

rm t/*.result.tsv.pdf
rm t/*.result.tsv.png

perl -I lib/ t/03-venn.t

# tree
perl -I lib/ script/plotr tree t/YDL184C.nwk

perl -I lib/ t/04-tree.t

# xlsx
perl -I lib/ script/plotr xlsx t/formats.xlsx -o stdout

perl -I lib/ t/05-xlsx.t

# tsv
perl -I lib/ script/plotr tsv t/mcox.05.result.tsv --header

perl -I lib/ t/06-tsv.t

# lines
perl -I lib/ script/plotr lines t/d1.tsv
perl -I lib/ script/plotr lines t/d1.tsv --style red

perl -I lib/ t/07-lines.t

# hist
Rscript -e '
    library(readr)
    set.seed(1234)
    df <- data.frame(
        weight=round(c(rnorm(200, mean=55, sd=5), rnorm(200, mean=65, sd=5))),
        sex=factor(rep(c("F", "M"), each=200))
    )
    write_tsv(df, "hist.tsv")
    '
mv hist.tsv t/

perl -I lib/ script/plotr hist t/hist.tsv \
    -p \
    --bins 2

perl -I lib/ script/plotr hist t/hist.tsv \
    -g 2 \
    -p \
    --bins 2

perl -I lib/ t/08-hist.t
