#!/usr/bin/perl
use strict;
use warnings;
use App::Plotr;

App::Plotr->run;

=head1 OVERVIEW

For help with App::Plotr, run "plotr help"

=cut

__END__

perl -I lib/ script/plotr help

# venn
perl -I lib/ script/plotr venn t/rocauc.result.tsv t/mcox.05.result.tsv t/mcox.result.tsv
perl -I lib/ script/plotr venn t/rocauc.result.tsv t/mcox.05.result.tsv --device png --percent

rm t/*.result.tsv.pdf
rm t/*.result.tsv.png

perl -I lib/ t/03-venn.t

# tree
perl -I lib/ script/plotr tree t/YDL184C.nwk

perl -I lib/ t/04-tree.t

# xlsx
perl -I lib/ script/plotr xlsx t/formats.xlsx -o stdout

perl -I lib/ t/05-xlsx.t

# lines
perl -I lib/ script/plotr lines t/d1.tsv
perl -I lib/ script/plotr lines t/d1.tsv --style red

perl -I lib/ script/plotr lines t/d1.tsv \
    --xl "Distance to indels ({italic(d)[1]})" \
    --yl "Nucleotide divergence ({italic(D)})" \
    --ymm 0.0,0.02 \
    --xmm 0,5

perl -I lib/ t/06-lines.t

# xlsx
perl -I lib/ script/plotr tsv t/mcox.05.result.tsv --header

perl -I lib/ script/plotr tsv t/rocauc.result.tsv --header --le 4:0.5 --ge 4:0.6 --bt 4:0.52:0.58

perl -I lib/ t/07-tsv.t
